[package]
name = "rest_api_vc"
version = "0.1.0"
authors = ["pawan <pawandhananjay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# validator_client = {path = "../../validator_store"}
eth2_ssz = "0.1.2"
types = { path = "../../eth2/types" }
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
serde_yaml = "0.8.11"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "2.3.0"
slog-term = "2.4.2"
tokio = "0.1.22"
futures = "0.1.29"
environment = { path = "../../lighthouse/environment" }
parking_lot = "0.7"
exit-future = "0.1.4"
eth2_ssz_derive = { path = "../../eth2/utils/ssz_derive" }
bls = { path = "../../eth2/utils/bls" }
http = "0.1"
hyper = "0.12"

[dev-dependencies]
remote_beacon_node = { path = "../../eth2/utils/remote_beacon_node" }
node_test_rig = { path = "../../tests/node_test_rig" }
