[workspace]
members = [
	"eth2/attester",
	"eth2/block_proposer",
	"eth2/fork_choice",
	"eth2/state_processing",
	"eth2/slashing",
	"eth2/types",
	"eth2/utils/bls",
	"eth2/utils/boolean-bitfield",
	"eth2/utils/hashing",
	"eth2/utils/honey-badger-split",
	"eth2/utils/int_to_bytes",
	"eth2/utils/slot_clock",
	"eth2/utils/ssz",
	"eth2/utils/ssz_derive",
	"eth2/utils/swap_or_not_shuffle",
	"eth2/utils/fisher_yates_shuffle",
	"beacon_node",
	"beacon_node/db",
	"beacon_node/beacon_chain",
	"beacon_node/beacon_chain/test_harness",
	"protos",
	"validator_client",
]
